name: "job_market_tracker"
version: "1.0.0"
config-version: 2

profile: "job_market_tracker"

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  job_market_tracker:
    staging:
      +schema: staging
      +materialized: view        # staging = vues légères
    marts:
      +schema: marts
      +materialized: table       # marts = tables 
