version: 2

sources:
  - name: raw
    database: JOBMARKET
    schema: PUBLIC
    description: "Données brutes chargées par le collecteur"
    tables:
      - name: RAW_JOBS
        description: "Offres d'emploi brutes collectées depuis azduna."
        columns:
          - name: ID
            description: "Identifiant unique de l'offre"
            tests:
              - not_null
          - name: TITLE
            tests:
              - not_null
          - name: SOURCE
            tests:
              - not_null
              - accepted_values:
                  values: ["adzuna"]
          - name: PUBLISHED_AT
            tests:
              - not_null

